#ifndef __ASSETS_H__
#define __ASSETS_H__


#define SFX_BEAR		_F(29)
#define SFX_BEAR_ID		29
#define SFX_HIT		_F(30)
#define SFX_HIT_ID		30
#define SFX_JETPACK		_F(31)
#define SFX_JETPACK_ID		31
#define SFX_JETPACK_FAIL		_F(32)
#define SFX_JETPACK_FAIL_ID		32
#define SFX_MAIA		_F(33)
#define SFX_MAIA_ID		33
#define SFX_POWERUP_01		_F(34)
#define SFX_POWERUP_01_ID		34
#define SFX_POWERUP_02		_F(35)
#define SFX_POWERUP_02_ID		35
#define SFX_POWERUP_03		_F(36)
#define SFX_POWERUP_03_ID		36
#define SFX_POWERUP_04		_F(37)
#define SFX_POWERUP_04_ID		37
#define SFX_START_FIGHT		_F(38)
#define SFX_START_FIGHT_ID		38
#define SFX_STEPS		_F(39)
#define SFX_STEPS_ID		39
#define SFX_WINGS		_F(40)
#define SFX_WINGS_ID		40
#define SFX_WINGS_FAIL		_F(41)
#define SFX_WINGS_FAIL_ID		41
#define BGM_MUSIC		_F(42)
#define BGM_MUSIC_ID		42
#define SPT_LR		_F(43)
#define SPT_LR_ID		43
#define SPT_UP		_F(44)
#define SPT_UP_ID		44
#define SPT_INTRO		_F(45)
#define SPT_INTRO_ID		45
#define SPT_INTRO_START		_F(46)
#define SPT_INTRO_START_ID		46
#define SPT_MENU		_F(47)
#define SPT_MENU_ID		47
#define SPT_BG		_F(48)
#define SPT_BG_ID		48
#define SPT_TUTORIAL		_F(49)
#define SPT_TUTORIAL_ID		49
#define SPT_THANKS		_F(50)
#define SPT_THANKS_ID		50
#define SPT_BIGORNA		_F(51)
#define SPT_BIGORNA_ID		51
#define SPT_GAMEOVER_PANDA		_F(52)
#define SPT_GAMEOVER_PANDA_ID		52
#define SPT_CREDITSBG		_F(53)
#define SPT_CREDITSBG_ID		53
#define SPT_PLAY		_F(54)
#define SPT_PLAY_ID		54
#define SPT_CREDITS		_F(55)
#define SPT_CREDITS_ID		55
#define SPT_OPTIONS		_F(56)
#define SPT_OPTIONS_ID		56
#define SPT_QUIT		_F(57)
#define SPT_QUIT_ID		57
#define SPT_BASE		_F(58)
#define SPT_BASE_ID		58
#define SPT_OPTIONS_TITLE		_F(59)
#define SPT_OPTIONS_TITLE_ID		59
#define SPT_PREV		_F(60)
#define SPT_PREV_ID		60
#define SPT_NEXT		_F(61)
#define SPT_NEXT_ID		61
#define SPT_CONTROL		_F(62)
#define SPT_CONTROL_ID		62
#define SPT_CONTROL_OPTION		_F(63)
#define SPT_CONTROL_OPTION_ID		63
#define SPT_VOLUME		_F(64)
#define SPT_VOLUME_ID		64
#define SPT_BGM		_F(65)
#define SPT_BGM_ID		65
#define SPT_SFX		_F(66)
#define SPT_SFX_ID		66
#define SPT_FULLSCREEN		_F(67)
#define SPT_FULLSCREEN_ID		67
#define SPT_CHECKBOX		_F(68)
#define SPT_CHECKBOX_ID		68
#define SPT_EXIT		_F(69)
#define SPT_EXIT_ID		69
#define SPT_BABY		_F(70)
#define SPT_BABY_ID		70
#define SPT_POWERUP_IMMOLATION		_F(71)
#define SPT_POWERUP_IMMOLATION_ID		71
#define SPT_POWERUP_SHIELD		_F(72)
#define SPT_POWERUP_SHIELD_ID		72
#define SPT_POWERUP_BABYSHIELD		_F(73)
#define SPT_POWERUP_BABYSHIELD_ID		73
#define SPT_POWERUP_ICONS		_F(74)
#define SPT_POWERUP_ICONS_ID		74
#define SPT_GAUGE		_F(75)
#define SPT_GAUGE_ID		75
#define SPT_PANDA		_F(76)
#define SPT_PANDA_ID		76
#define SPT_MAIA		_F(77)
#define SPT_MAIA_ID		77
#define SPT_TILESET_TILESET01		_F(78)
#define SPT_TILESET_TILESET01_ID		78
#define MAP_LV1		_F(79)
#define MAP_LV1_ID		79
#define MAP_LV2		_F(80)
#define MAP_LV2_ID		80
#define MAP_LV3		_F(81)
#define MAP_LV3_ID		81
#define MAP_LV4		_F(82)
#define MAP_LV4_ID		82
#define MAP_LV5		_F(83)
#define MAP_LV5_ID		83


#endif // __ASSETS_H__
